apiVersion: v1
kind: Service
metadata:
  name: accesslog
spec:
  ports:
    - port: 80
      targetPort: api
  selector:
    app: apod-log
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apod-log
spec:
  selector:
    matchLabels:
      app: apod-log
  template:
    metadata:
      labels:
        app: apod-log
    spec:
      containers:
        - name: api
          image: access-log
          ports:
            - containerPort: 80
              name: api
