name: Update version tags

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tags"
        required: true

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo tag
        run: echo '${{ github.event.inputs.tag }}'